/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowcasesShoyaKajitaRouteImport } from './routes/showcases/shoya-kajita'
import { Route as ShowcasesFirewatchRouteImport } from './routes/showcases/firewatch'
import { Route as ReferencesSergeTyutikRouteImport } from './routes/references/serge-tyutik'
import { Route as ReferencesMarathonRouteImport } from './routes/references/marathon'
import { Route as ReferencesKubaRouteImport } from './routes/references/kuba'
import { Route as ReferencesJamesLeeRouteImport } from './routes/references/james-lee'
import { Route as RExpMoodboardRouteImport } from './routes/r-exp/moodboard'
import { Route as RExpLogoRefsRouteImport } from './routes/r-exp/logo-refs'

const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesShoyaKajitaRoute = ShowcasesShoyaKajitaRouteImport.update({
  id: '/showcases/shoya-kajita',
  path: '/showcases/shoya-kajita',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcasesFirewatchRoute = ShowcasesFirewatchRouteImport.update({
  id: '/showcases/firewatch',
  path: '/showcases/firewatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesSergeTyutikRoute = ReferencesSergeTyutikRouteImport.update({
  id: '/references/serge-tyutik',
  path: '/references/serge-tyutik',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesMarathonRoute = ReferencesMarathonRouteImport.update({
  id: '/references/marathon',
  path: '/references/marathon',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesKubaRoute = ReferencesKubaRouteImport.update({
  id: '/references/kuba',
  path: '/references/kuba',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesJamesLeeRoute = ReferencesJamesLeeRouteImport.update({
  id: '/references/james-lee',
  path: '/references/james-lee',
  getParentRoute: () => rootRouteImport,
} as any)
const RExpMoodboardRoute = RExpMoodboardRouteImport.update({
  id: '/r-exp/moodboard',
  path: '/r-exp/moodboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RExpLogoRefsRoute = RExpLogoRefsRouteImport.update({
  id: '/r-exp/logo-refs',
  path: '/r-exp/logo-refs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/notes': typeof NotesRoute
  '/readme': typeof ReadmeRoute
  '/r-exp/logo-refs': typeof RExpLogoRefsRoute
  '/r-exp/moodboard': typeof RExpMoodboardRoute
  '/references/james-lee': typeof ReferencesJamesLeeRoute
  '/references/kuba': typeof ReferencesKubaRoute
  '/references/marathon': typeof ReferencesMarathonRoute
  '/references/serge-tyutik': typeof ReferencesSergeTyutikRoute
  '/showcases/firewatch': typeof ShowcasesFirewatchRoute
  '/showcases/shoya-kajita': typeof ShowcasesShoyaKajitaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/notes': typeof NotesRoute
  '/readme': typeof ReadmeRoute
  '/r-exp/logo-refs': typeof RExpLogoRefsRoute
  '/r-exp/moodboard': typeof RExpMoodboardRoute
  '/references/james-lee': typeof ReferencesJamesLeeRoute
  '/references/kuba': typeof ReferencesKubaRoute
  '/references/marathon': typeof ReferencesMarathonRoute
  '/references/serge-tyutik': typeof ReferencesSergeTyutikRoute
  '/showcases/firewatch': typeof ShowcasesFirewatchRoute
  '/showcases/shoya-kajita': typeof ShowcasesShoyaKajitaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/notes': typeof NotesRoute
  '/readme': typeof ReadmeRoute
  '/r-exp/logo-refs': typeof RExpLogoRefsRoute
  '/r-exp/moodboard': typeof RExpMoodboardRoute
  '/references/james-lee': typeof ReferencesJamesLeeRoute
  '/references/kuba': typeof ReferencesKubaRoute
  '/references/marathon': typeof ReferencesMarathonRoute
  '/references/serge-tyutik': typeof ReferencesSergeTyutikRoute
  '/showcases/firewatch': typeof ShowcasesFirewatchRoute
  '/showcases/shoya-kajita': typeof ShowcasesShoyaKajitaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/notes'
    | '/readme'
    | '/r-exp/logo-refs'
    | '/r-exp/moodboard'
    | '/references/james-lee'
    | '/references/kuba'
    | '/references/marathon'
    | '/references/serge-tyutik'
    | '/showcases/firewatch'
    | '/showcases/shoya-kajita'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/notes'
    | '/readme'
    | '/r-exp/logo-refs'
    | '/r-exp/moodboard'
    | '/references/james-lee'
    | '/references/kuba'
    | '/references/marathon'
    | '/references/serge-tyutik'
    | '/showcases/firewatch'
    | '/showcases/shoya-kajita'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/notes'
    | '/readme'
    | '/r-exp/logo-refs'
    | '/r-exp/moodboard'
    | '/references/james-lee'
    | '/references/kuba'
    | '/references/marathon'
    | '/references/serge-tyutik'
    | '/showcases/firewatch'
    | '/showcases/shoya-kajita'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  NotesRoute: typeof NotesRoute
  ReadmeRoute: typeof ReadmeRoute
  RExpLogoRefsRoute: typeof RExpLogoRefsRoute
  RExpMoodboardRoute: typeof RExpMoodboardRoute
  ReferencesJamesLeeRoute: typeof ReferencesJamesLeeRoute
  ReferencesKubaRoute: typeof ReferencesKubaRoute
  ReferencesMarathonRoute: typeof ReferencesMarathonRoute
  ReferencesSergeTyutikRoute: typeof ReferencesSergeTyutikRoute
  ShowcasesFirewatchRoute: typeof ShowcasesFirewatchRoute
  ShowcasesShoyaKajitaRoute: typeof ShowcasesShoyaKajitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/shoya-kajita': {
      id: '/showcases/shoya-kajita'
      path: '/showcases/shoya-kajita'
      fullPath: '/showcases/shoya-kajita'
      preLoaderRoute: typeof ShowcasesShoyaKajitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcases/firewatch': {
      id: '/showcases/firewatch'
      path: '/showcases/firewatch'
      fullPath: '/showcases/firewatch'
      preLoaderRoute: typeof ShowcasesFirewatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/serge-tyutik': {
      id: '/references/serge-tyutik'
      path: '/references/serge-tyutik'
      fullPath: '/references/serge-tyutik'
      preLoaderRoute: typeof ReferencesSergeTyutikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/marathon': {
      id: '/references/marathon'
      path: '/references/marathon'
      fullPath: '/references/marathon'
      preLoaderRoute: typeof ReferencesMarathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/kuba': {
      id: '/references/kuba'
      path: '/references/kuba'
      fullPath: '/references/kuba'
      preLoaderRoute: typeof ReferencesKubaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/james-lee': {
      id: '/references/james-lee'
      path: '/references/james-lee'
      fullPath: '/references/james-lee'
      preLoaderRoute: typeof ReferencesJamesLeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r-exp/moodboard': {
      id: '/r-exp/moodboard'
      path: '/r-exp/moodboard'
      fullPath: '/r-exp/moodboard'
      preLoaderRoute: typeof RExpMoodboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r-exp/logo-refs': {
      id: '/r-exp/logo-refs'
      path: '/r-exp/logo-refs'
      fullPath: '/r-exp/logo-refs'
      preLoaderRoute: typeof RExpLogoRefsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  NotesRoute: NotesRoute,
  ReadmeRoute: ReadmeRoute,
  RExpLogoRefsRoute: RExpLogoRefsRoute,
  RExpMoodboardRoute: RExpMoodboardRoute,
  ReferencesJamesLeeRoute: ReferencesJamesLeeRoute,
  ReferencesKubaRoute: ReferencesKubaRoute,
  ReferencesMarathonRoute: ReferencesMarathonRoute,
  ReferencesSergeTyutikRoute: ReferencesSergeTyutikRoute,
  ShowcasesFirewatchRoute: ShowcasesFirewatchRoute,
  ShowcasesShoyaKajitaRoute: ShowcasesShoyaKajitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
