/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferencesKubaRouteImport } from './routes/references/kuba'
import { Route as RExpMoodboardRouteImport } from './routes/r-exp/moodboard'
import { Route as RExpLogoRefsRouteImport } from './routes/r-exp/logo-refs'

const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesKubaRoute = ReferencesKubaRouteImport.update({
  id: '/references/kuba',
  path: '/references/kuba',
  getParentRoute: () => rootRouteImport,
} as any)
const RExpMoodboardRoute = RExpMoodboardRouteImport.update({
  id: '/r-exp/moodboard',
  path: '/r-exp/moodboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RExpLogoRefsRoute = RExpLogoRefsRouteImport.update({
  id: '/r-exp/logo-refs',
  path: '/r-exp/logo-refs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/readme': typeof ReadmeRoute
  '/r-exp/logo-refs': typeof RExpLogoRefsRoute
  '/r-exp/moodboard': typeof RExpMoodboardRoute
  '/references/kuba': typeof ReferencesKubaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/readme': typeof ReadmeRoute
  '/r-exp/logo-refs': typeof RExpLogoRefsRoute
  '/r-exp/moodboard': typeof RExpMoodboardRoute
  '/references/kuba': typeof ReferencesKubaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes': typeof NotesRoute
  '/readme': typeof ReadmeRoute
  '/r-exp/logo-refs': typeof RExpLogoRefsRoute
  '/r-exp/moodboard': typeof RExpMoodboardRoute
  '/references/kuba': typeof ReferencesKubaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/readme'
    | '/r-exp/logo-refs'
    | '/r-exp/moodboard'
    | '/references/kuba'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes'
    | '/readme'
    | '/r-exp/logo-refs'
    | '/r-exp/moodboard'
    | '/references/kuba'
  id:
    | '__root__'
    | '/'
    | '/notes'
    | '/readme'
    | '/r-exp/logo-refs'
    | '/r-exp/moodboard'
    | '/references/kuba'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRoute
  ReadmeRoute: typeof ReadmeRoute
  RExpLogoRefsRoute: typeof RExpLogoRefsRoute
  RExpMoodboardRoute: typeof RExpMoodboardRoute
  ReferencesKubaRoute: typeof ReferencesKubaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/kuba': {
      id: '/references/kuba'
      path: '/references/kuba'
      fullPath: '/references/kuba'
      preLoaderRoute: typeof ReferencesKubaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r-exp/moodboard': {
      id: '/r-exp/moodboard'
      path: '/r-exp/moodboard'
      fullPath: '/r-exp/moodboard'
      preLoaderRoute: typeof RExpMoodboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r-exp/logo-refs': {
      id: '/r-exp/logo-refs'
      path: '/r-exp/logo-refs'
      fullPath: '/r-exp/logo-refs'
      preLoaderRoute: typeof RExpLogoRefsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRoute,
  ReadmeRoute: ReadmeRoute,
  RExpLogoRefsRoute: RExpLogoRefsRoute,
  RExpMoodboardRoute: RExpMoodboardRoute,
  ReferencesKubaRoute: ReferencesKubaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
